---

version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ~/.config/git:/root/.config/git:ro
      - ~/.ssh:/root/.ssh-localhost:ro
      - ${SSH_AUTH_SOCK}:/ssh-agent:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/ansible-role-rocketchat
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    working_dir: /ansible-role-rocketchat
    command: sleep infinity

...
